// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(braird_coreFFI)
import braird_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_braird_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_braird_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol VaultProtocol : AnyObject {
    
    /**
     * 64-char lowercase hex content-dedup tag (HMAC-SHA256, 64-byte subkey).
     */
    func contentTag(text: String, bookId: String?)  -> String
    
    /**
     * Decrypt an enc:v1/enc:v2 payload produced by this core OR by the PWA.
     */
    func decryptNote(noteId: String?, ciphertext: String) throws  -> String
    
    /**
     * enc:v2 when `note_id` is `Some` (AAD = UTF-8 noteId); enc:v1 when `None`. Fresh
     * random 12-byte IV per call.
     */
    func encryptNote(noteId: String?, plaintext: String)  -> String
    
    /**
     * Open a blob produced by [`Vault::seal_bytes`].
     */
    func openBytes(sealed: Data, aad: String) throws  -> Data
    
    /**
     * PIN-wrap the owned MK for device transfer (PBKDF2-SHA256 @ 600k → AES-256-GCM).
     */
    func pinWrap(pin: String)  -> WrappedBlob
    
    /**
     * Re-wrap the owned MK for a different credential/device. The Vault already holds
     * the MK, so this is a fresh wrap under `new_prf` (multi-device add).
     */
    func rewrap(newPrf: Data)  -> WrappedBlob
    
    /**
     * Seal arbitrary bytes (e.g. an embedding vector) at rest: `[0x02][IV][ct]`,
     * AAD = noteId. Fresh random IV per call.
     */
    func sealBytes(bytes: Data, aad: String)  -> Data
    
    /**
     * Wrap the owned MK with a PRF-derived key → a storable prf-v1 blob. Salt (32B)
     * and IV (12B) are generated in-core with the CSPRNG — no nonce-reuse footgun.
     */
    func wrapWithPrf(prf: Data)  -> WrappedBlob
    
}

open class Vault:
    VaultProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_braird_core_fn_clone_vault(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_braird_core_fn_free_vault(pointer, $0) }
    }

    
    /**
     * Generate a fresh random 256-bit Master Key in-core. The MK never leaves the
     * handle; persist it with [`Vault::wrap_with_prf`].
     */
public static func generate() -> Vault {
    return try!  FfiConverterTypeVault.lift(try! rustCall() {
    uniffi_braird_core_fn_constructor_vault_generate($0
    )
})
}
    
    /**
     * Redeem a PIN-encrypted device-transfer blob on a new device (PBKDF2 @ 600k).
     */
public static func redeemPinTransfer(transferBlob: WrappedBlob, pin: String)throws  -> Vault {
    return try  FfiConverterTypeVault.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_braird_core_fn_constructor_vault_redeem_pin_transfer(
        FfiConverterTypeWrappedBlob.lower(transferBlob),
        FfiConverterString.lower(pin),$0
    )
})
}
    
    /**
     * Unlock by decrypting a stored prf-v1 blob with raw PRF bytes (the WebAuthn PRF
     * output, fed to HKDF unchanged). The recovered MK stays inside the handle.
     */
public static func unlock(prf: Data, blob: WrappedBlob)throws  -> Vault {
    return try  FfiConverterTypeVault.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_braird_core_fn_constructor_vault_unlock(
        FfiConverterData.lower(prf),
        FfiConverterTypeWrappedBlob.lower(blob),$0
    )
})
}
    

    
    /**
     * 64-char lowercase hex content-dedup tag (HMAC-SHA256, 64-byte subkey).
     */
open func contentTag(text: String, bookId: String?) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_content_tag(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterOptionString.lower(bookId),$0
    )
})
}
    
    /**
     * Decrypt an enc:v1/enc:v2 payload produced by this core OR by the PWA.
     */
open func decryptNote(noteId: String?, ciphertext: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_braird_core_fn_method_vault_decrypt_note(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(noteId),
        FfiConverterString.lower(ciphertext),$0
    )
})
}
    
    /**
     * enc:v2 when `note_id` is `Some` (AAD = UTF-8 noteId); enc:v1 when `None`. Fresh
     * random 12-byte IV per call.
     */
open func encryptNote(noteId: String?, plaintext: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_encrypt_note(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(noteId),
        FfiConverterString.lower(plaintext),$0
    )
})
}
    
    /**
     * Open a blob produced by [`Vault::seal_bytes`].
     */
open func openBytes(sealed: Data, aad: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_braird_core_fn_method_vault_open_bytes(self.uniffiClonePointer(),
        FfiConverterData.lower(sealed),
        FfiConverterString.lower(aad),$0
    )
})
}
    
    /**
     * PIN-wrap the owned MK for device transfer (PBKDF2-SHA256 @ 600k → AES-256-GCM).
     */
open func pinWrap(pin: String) -> WrappedBlob {
    return try!  FfiConverterTypeWrappedBlob.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_pin_wrap(self.uniffiClonePointer(),
        FfiConverterString.lower(pin),$0
    )
})
}
    
    /**
     * Re-wrap the owned MK for a different credential/device. The Vault already holds
     * the MK, so this is a fresh wrap under `new_prf` (multi-device add).
     */
open func rewrap(newPrf: Data) -> WrappedBlob {
    return try!  FfiConverterTypeWrappedBlob.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_rewrap(self.uniffiClonePointer(),
        FfiConverterData.lower(newPrf),$0
    )
})
}
    
    /**
     * Seal arbitrary bytes (e.g. an embedding vector) at rest: `[0x02][IV][ct]`,
     * AAD = noteId. Fresh random IV per call.
     */
open func sealBytes(bytes: Data, aad: String) -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_seal_bytes(self.uniffiClonePointer(),
        FfiConverterData.lower(bytes),
        FfiConverterString.lower(aad),$0
    )
})
}
    
    /**
     * Wrap the owned MK with a PRF-derived key → a storable prf-v1 blob. Salt (32B)
     * and IV (12B) are generated in-core with the CSPRNG — no nonce-reuse footgun.
     */
open func wrapWithPrf(prf: Data) -> WrappedBlob {
    return try!  FfiConverterTypeWrappedBlob.lift(try! rustCall() {
    uniffi_braird_core_fn_method_vault_wrap_with_prf(self.uniffiClonePointer(),
        FfiConverterData.lower(prf),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVault: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Vault

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Vault {
        return Vault(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Vault) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Vault {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Vault, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVault_lift(_ pointer: UnsafeMutableRawPointer) throws -> Vault {
    return try FfiConverterTypeVault.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVault_lower(_ value: Vault) -> UnsafeMutableRawPointer {
    return FfiConverterTypeVault.lower(value)
}


/**
 * A stored `prf-v1` / PIN-transfer wrapped-key blob — base64 fields, exactly the
 * JS `{ wrappedKey, iv, salt }` shape. Standard base64, NOT url-safe (frozen).
 */
public struct WrappedBlob {
    public var wrappedKey: String
    public var iv: String
    public var salt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(wrappedKey: String, iv: String, salt: String) {
        self.wrappedKey = wrappedKey
        self.iv = iv
        self.salt = salt
    }
}



extension WrappedBlob: Equatable, Hashable {
    public static func ==(lhs: WrappedBlob, rhs: WrappedBlob) -> Bool {
        if lhs.wrappedKey != rhs.wrappedKey {
            return false
        }
        if lhs.iv != rhs.iv {
            return false
        }
        if lhs.salt != rhs.salt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(wrappedKey)
        hasher.combine(iv)
        hasher.combine(salt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWrappedBlob: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WrappedBlob {
        return
            try WrappedBlob(
                wrappedKey: FfiConverterString.read(from: &buf), 
                iv: FfiConverterString.read(from: &buf), 
                salt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WrappedBlob, into buf: inout [UInt8]) {
        FfiConverterString.write(value.wrappedKey, into: &buf)
        FfiConverterString.write(value.iv, into: &buf)
        FfiConverterString.write(value.salt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWrappedBlob_lift(_ buf: RustBuffer) throws -> WrappedBlob {
    return try FfiConverterTypeWrappedBlob.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWrappedBlob_lower(_ value: WrappedBlob) -> RustBuffer {
    return FfiConverterTypeWrappedBlob.lower(value)
}


/**
 * Errors that cross the FFI. Deliberately coarse: never leak key material or
 * distinguish auth-tag failure modes to callers.
 */
public enum CryptoError {

    
    
    case DecryptFailed
    case BadInput(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DecryptFailed
        case 2: return .BadInput(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .DecryptFailed:
            writeInt(&buf, Int32(1))
        
        
        case let .BadInput(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension CryptoError: Equatable, Hashable {}

extension CryptoError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_braird_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_content_tag() != 23104) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_decrypt_note() != 2957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_encrypt_note() != 22447) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_open_bytes() != 24917) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_pin_wrap() != 28802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_rewrap() != 61446) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_seal_bytes() != 63933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_method_vault_wrap_with_prf() != 28929) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_constructor_vault_generate() != 65080) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_constructor_vault_redeem_pin_transfer() != 25070) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_braird_core_checksum_constructor_vault_unlock() != 13169) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all